name: sliding_puzzle
version: 1.0.0
publish_to: 'none'
description: A simple Flutter sliding puzzle game.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
